Aviva.FizzBuzz/FizzBuzz.Web/Models/FizzBuzzModel.cs
namespace FizzBuzz.Web.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using FizzBuzz.Business;

    public class FizzBuzzModel
    {
        public const int PageSize = 20;
        private int? fizzbuzznumber;
        public FizzBuzzPaging fizzbuzzPaging { get; set; }

        public FizzBuzzModel()
        {
            this.fizzbuzzPaging = new FizzBuzzPaging();
        }

        [Required]
        [Display(Name = "Please enter the number")]
        [Range(1, 1000, ErrorMessage = "Please enter a value between 1 and 1000")]
        public int? FizzBuzzNumber
        {
            get
            {
                return this.fizzbuzznumber;
            }

            set
            {
                this.fizzbuzznumber = value;
                this.fizzbuzzPaging.PageIndex = 1;
                this.fizzbuzzPaging.PageCount = Convert.ToInt32(this.fizzbuzznumber) / PageSize;
                this.fizzbuzzPaging.PageCount = (this.fizzbuzznumber % PageSize) == 0 ? this.fizzbuzzPaging.PageCount : this.fizzbuzzPaging.PageCount + 1;
            }
        }

        public List<IFizzBuzz> FizzBuzzNumberList { get; set; }
    }
}

Aviva.FizzBuzz/FizzBuzz.Web/Models/FizzBuzzPaging.cs
namespace FizzBuzz.Web.Models
{
    public class FizzBuzzPaging
    {
        public FizzBuzzPaging()
        {
            this.PageIndex = 1;
        }

        public int PageIndex { get; set; }
        public int PageCount { get; set; }
    }
}

Aviva.FizzBuzz/FizzBuzz.Web/Controllers/FizzBuzzController.cs
namespace FizzBuzz.Web.Controllers
{
    using System.Diagnostics.CodeAnalysis;
    using System.Web.Mvc;
    using FizzBuzz.Business;
    using FizzBuzz.Web.Attributes;
    using FizzBuzz.Web.Mappers;
    using FizzBuzz.Web.Models;

    public class FizzBuzzController : Controller
    {
        private readonly IFizzBuzzLogic fizzbuzzLogic;

        public FizzBuzzController(IFizzBuzzLogic fizzBuzzLogic)
        {
            this.fizzbuzzLogic = fizzBuzzLogic;
        }

        [HttpGet]
        public ActionResult FizzBuzzView()
        {
            return this.View("FizzBuzzView", new FizzBuzzModel());
        }

        [HttpPost]
        [Button(Name = "DisplayList")]
        [ActionName("FizzBuzzView")]
        public ActionResult FizzBuzzView(FizzBuzzModel fizzBuzzModel)
        {
            var resultSet = this.SetFizzBuzzModel(fizzBuzzModel, string.Empty);
            return this.View("FizzBuzzView", resultSet);
        }

        [HttpPost]
        [Button(Name = "Next")]
        [ActionName("FizzBuzzView")]
        public ActionResult FizzBuzzViewNext(FizzBuzzModel fizzBuzzModel)
        {
            var resultSet = this.SetFizzBuzzModel(fizzBuzzModel, "next");
            return this.View("FizzBuzzView", resultSet);
        }

        [HttpPost]
        [Button(Name = "Previous")]
        [ActionName("FizzBuzzView")]
        public ActionResult FizzBuzzViewPrevious(FizzBuzzModel fizzBuzzModel)
        {
            var resultSet = this.SetFizzBuzzModel(fizzBuzzModel, "previous");
            return this.View("FizzBuzzView", resultSet);
        }

        private FizzBuzzModel SetFizzBuzzModel(FizzBuzzModel fizzBuzzModel, string caseSwitchPaging)
        {
            var result = new FizzBuzzModel { FizzBuzzNumber = fizzBuzzModel.FizzBuzzNumber };
            FizzBuzzPagingMapper.SetFizzBuzzListPaging(result, caseSwitchPaging, this.TempData["FizzBuzzPage"]);
            if (this.ModelState.IsValid)
            {
                this.FillFizzBuzzResultSet(result);
            }

            this.TempData["FizzBuzzPage"] = result.fizzbuzzPaging;
            return result;
        }

        [SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1118:ParameterMustNotSpanMultipleLines", Justification = "Reviewed. Suppression is OK here.")]
        [NonAction]
        private void FillFizzBuzzResultSet(FizzBuzzModel fizzBuzzModel)
        {
            var startIndex = (fizzBuzzModel.fizzbuzzPaging.PageIndex - 1) * FizzBuzzModel.PageSize;
            if (fizzBuzzModel.FizzBuzzNumber == null)
            {
                return;
            }

            fizzBuzzModel.FizzBuzzNumberList = this.fizzbuzzLogic.GetFizzBuzzNumbersList(fizzBuzzModel.FizzBuzzNumber.Value);
            fizzBuzzModel.FizzBuzzNumberList = fizzBuzzModel.FizzBuzzNumberList.GetRange(
                startIndex,
                fizzBuzzModel.FizzBuzzNumber.Value - startIndex < FizzBuzzModel.PageSize
                    ? fizzBuzzModel.FizzBuzzNumber.Value - startIndex
                    : FizzBuzzModel.PageSize);
        }
    }
}

Aviva.FizzBuzz/FizzBuzz.Web/Views/FizzBuzz/FizzBuzzView.cshtml
@model FizzBuzz.Web.Models.FizzBuzzModel

@{
    ViewBag.Title = "Basic FizzBuzz Application";
}

<h2>Input Screen</h2>
@using (Html.BeginForm("FizzBuzzView", "FizzBuzz"))
{
    <div>
        <fieldset>
            <table>
                <tr>
                    <td>
                        <div class="editor-label">
                            @Html.LabelFor(m => m.FizzBuzzNumber)
                        </div>
                    </td>
                    <td>
                        <div class="editor-field">
                            @Html.TextBoxFor(m => m.FizzBuzzNumber)
                            @Html.ValidationMessageFor(m => m.FizzBuzzNumber)
                        </div>
                    </td>
                    <td>
                        <div class="editor-field">
                            <input type="submit" name="DisplayList" value="Display List" />
                        </div>
                    </td>
                </tr>
            </table>
        </fieldset>
    </div>

    if (Model.FizzBuzzNumberList != null && Model.FizzBuzzNumberList.Count > 0)
    {
    <div>
        <fieldset>
            <table>
                <tr>
                    <td width="50%">Showing Page <b>@Model.fizzbuzzPaging.PageIndex</b> of <b>@Model.fizzbuzzPaging.PageCount</b> Pages
                    </td>
                    <td width="50%" align="right">
                        <input type="submit" name="Previous" value="Previous" id="Previous" @{ if (Model.fizzbuzzPaging.PageIndex == 1 == true)
                                                                                               { 
             @:disabled="disabled" 
        } }/>
                        <input type="submit" name="Next" value="Next" id="Next" @{ if (Model.fizzbuzzPaging.PageIndex == Model.fizzbuzzPaging.PageCount == true)
                                                                                               { 
             @:disabled="disabled" 
        } }/>
                    </td>
                </tr>
                @foreach (var number in Model.FizzBuzzNumberList)
                {
                    <tr>
                        <td colspan="2">
                            @if (string.IsNullOrEmpty(number.MessageStyle))
                            {
                                <div class="@number">@number.DisplayMessage</div>
                            }
                            else
                            {
                                <div style="color:@number.MessageStyle" class="@number">@number.DisplayMessage</div>
                            }
                        </td>
                    </tr>
                }
            </table>
        </fieldset>
        <br />
    </div>
    <br />
  
    }
}

Aviva.FizzBuzz/FizzBuzz.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width"/>
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
@RenderBody()

@Scripts.Render("~/bundles/jquery")
@RenderSection("scripts", false)
</body>
</html>